name: Keep Streamlit Awake

# Agenda para rodar periodicamente
on:
  schedule:
    - cron: '0 */10 * * *'  # a cada 10 horas
  workflow_dispatch:  # permite rodar manualmente

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create empty commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Keep Streamlit awake"
          git push
