[theme]
primaryColor      = "#61D4C6"
backgroundColor   = "#0B111A"
secondaryBackgroundColor = "#151D2A"
textColor         = "#F0F4F8"
font              = "sans serif"

[server]
headless          = true
enableCORS        = false
enableXsrfProtection = false
maxUploadSize     = 50

[browser]
gatherUsageStats  = false
