[theme]
base              = "dark"
primaryColor      = "#76D5C5"
backgroundColor   = "#0C1518"
secondaryBackgroundColor = "#142126"
textColor         = "#EEF4F2"
font              = "sans serif"

[server]
headless          = true
enableCORS        = true
enableXsrfProtection = true
maxUploadSize     = 50

[browser]
gatherUsageStats  = false
